/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvRequestSellerParty;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestBlanketOrderReference;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestConsignee;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestOrderLineInner;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestPaymentTerms;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestSellerParty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * EDIWheelC11OrderCreationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class EDIWheelC11OrderCreationRequest {
  public static final String SERIALIZED_NAME_DOCUMENT_I_D = "DocumentID";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_I_D)
  @javax.annotation.Nonnull
  private String documentID;

  public static final String SERIALIZED_NAME_VARIANT = "Variant";
  @SerializedName(SERIALIZED_NAME_VARIANT)
  @javax.annotation.Nullable
  private String variant;

  public static final String SERIALIZED_NAME_EARLIEST_DELIVERY_DATE = "EarliestDeliveryDate";
  @SerializedName(SERIALIZED_NAME_EARLIEST_DELIVERY_DATE)
  @javax.annotation.Nullable
  private String earliestDeliveryDate;

  public static final String SERIALIZED_NAME_TRANSPORT_PRIORITY = "TransportPriority";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_PRIORITY)
  @javax.annotation.Nullable
  private String transportPriority;

  public static final String SERIALIZED_NAME_CAMPAIGN = "Campaign";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN)
  @javax.annotation.Nullable
  private String campaign;

  public static final String SERIALIZED_NAME_PICK_UP = "PickUp";
  @SerializedName(SERIALIZED_NAME_PICK_UP)
  @javax.annotation.Nullable
  private String pickUp;

  public static final String SERIALIZED_NAME_DELIVERY_OPTION = "DeliveryOption";
  @SerializedName(SERIALIZED_NAME_DELIVERY_OPTION)
  @javax.annotation.Nullable
  private String deliveryOption;

  public static final String SERIALIZED_NAME_DELIVERY_REMARKS = "DeliveryRemarks";
  @SerializedName(SERIALIZED_NAME_DELIVERY_REMARKS)
  @javax.annotation.Nullable
  private String deliveryRemarks;

  public static final String SERIALIZED_NAME_BLANKET_ORDER_REFERENCE = "BlanketOrderReference";
  @SerializedName(SERIALIZED_NAME_BLANKET_ORDER_REFERENCE)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestBlanketOrderReference blanketOrderReference;

  public static final String SERIALIZED_NAME_CUSTOMER_REFERENCE = "CustomerReference";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REFERENCE)
  @javax.annotation.Nonnull
  private EDIWheelC11OrderCreationRequestBlanketOrderReference customerReference;

  public static final String SERIALIZED_NAME_SELLER_PARTY = "SellerParty";
  @SerializedName(SERIALIZED_NAME_SELLER_PARTY)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestSellerParty sellerParty;

  public static final String SERIALIZED_NAME_SUPPLIER_PARTY = "SupplierParty";
  @SerializedName(SERIALIZED_NAME_SUPPLIER_PARTY)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestSellerParty supplierParty;

  public static final String SERIALIZED_NAME_BUYER_PARTY = "BuyerParty";
  @SerializedName(SERIALIZED_NAME_BUYER_PARTY)
  @javax.annotation.Nonnull
  private EDIWheelC11OrderCreationRequestSellerParty buyerParty;

  public static final String SERIALIZED_NAME_ORDERING_PARTY = "OrderingParty";
  @SerializedName(SERIALIZED_NAME_ORDERING_PARTY)
  @javax.annotation.Nullable
  private EDIWheelC10DesadvRequestSellerParty orderingParty;

  public static final String SERIALIZED_NAME_CONSIGNEE = "Consignee";
  @SerializedName(SERIALIZED_NAME_CONSIGNEE)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestConsignee consignee;

  public static final String SERIALIZED_NAME_CONTRACT = "Contract";
  @SerializedName(SERIALIZED_NAME_CONTRACT)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestBlanketOrderReference contract;

  public static final String SERIALIZED_NAME_PAYMENT_TERMS = "PaymentTerms";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TERMS)
  @javax.annotation.Nullable
  private EDIWheelC11OrderCreationRequestPaymentTerms paymentTerms;

  public static final String SERIALIZED_NAME_ORDER_LINE = "OrderLine";
  @SerializedName(SERIALIZED_NAME_ORDER_LINE)
  @javax.annotation.Nullable
  private List<EDIWheelC11OrderCreationRequestOrderLineInner> orderLine = new ArrayList<>();

  public EDIWheelC11OrderCreationRequest() {
  }

  public EDIWheelC11OrderCreationRequest documentID(@javax.annotation.Nonnull String documentID) {
    this.documentID = documentID;
    return this;
  }

  /**
   * Get documentID
   * @return documentID
   */
  @javax.annotation.Nonnull
  public String getDocumentID() {
    return documentID;
  }

  public void setDocumentID(@javax.annotation.Nonnull String documentID) {
    this.documentID = documentID;
  }


  public EDIWheelC11OrderCreationRequest variant(@javax.annotation.Nullable String variant) {
    this.variant = variant;
    return this;
  }

  /**
   * Get variant
   * @return variant
   */
  @javax.annotation.Nullable
  public String getVariant() {
    return variant;
  }

  public void setVariant(@javax.annotation.Nullable String variant) {
    this.variant = variant;
  }


  public EDIWheelC11OrderCreationRequest earliestDeliveryDate(@javax.annotation.Nullable String earliestDeliveryDate) {
    this.earliestDeliveryDate = earliestDeliveryDate;
    return this;
  }

  /**
   * Get earliestDeliveryDate
   * @return earliestDeliveryDate
   */
  @javax.annotation.Nullable
  public String getEarliestDeliveryDate() {
    return earliestDeliveryDate;
  }

  public void setEarliestDeliveryDate(@javax.annotation.Nullable String earliestDeliveryDate) {
    this.earliestDeliveryDate = earliestDeliveryDate;
  }


  public EDIWheelC11OrderCreationRequest transportPriority(@javax.annotation.Nullable String transportPriority) {
    this.transportPriority = transportPriority;
    return this;
  }

  /**
   * Get transportPriority
   * @return transportPriority
   */
  @javax.annotation.Nullable
  public String getTransportPriority() {
    return transportPriority;
  }

  public void setTransportPriority(@javax.annotation.Nullable String transportPriority) {
    this.transportPriority = transportPriority;
  }


  public EDIWheelC11OrderCreationRequest campaign(@javax.annotation.Nullable String campaign) {
    this.campaign = campaign;
    return this;
  }

  /**
   * Get campaign
   * @return campaign
   */
  @javax.annotation.Nullable
  public String getCampaign() {
    return campaign;
  }

  public void setCampaign(@javax.annotation.Nullable String campaign) {
    this.campaign = campaign;
  }


  public EDIWheelC11OrderCreationRequest pickUp(@javax.annotation.Nullable String pickUp) {
    this.pickUp = pickUp;
    return this;
  }

  /**
   * Get pickUp
   * @return pickUp
   */
  @javax.annotation.Nullable
  public String getPickUp() {
    return pickUp;
  }

  public void setPickUp(@javax.annotation.Nullable String pickUp) {
    this.pickUp = pickUp;
  }


  public EDIWheelC11OrderCreationRequest deliveryOption(@javax.annotation.Nullable String deliveryOption) {
    this.deliveryOption = deliveryOption;
    return this;
  }

  /**
   * Get deliveryOption
   * @return deliveryOption
   */
  @javax.annotation.Nullable
  public String getDeliveryOption() {
    return deliveryOption;
  }

  public void setDeliveryOption(@javax.annotation.Nullable String deliveryOption) {
    this.deliveryOption = deliveryOption;
  }


  public EDIWheelC11OrderCreationRequest deliveryRemarks(@javax.annotation.Nullable String deliveryRemarks) {
    this.deliveryRemarks = deliveryRemarks;
    return this;
  }

  /**
   * Get deliveryRemarks
   * @return deliveryRemarks
   */
  @javax.annotation.Nullable
  public String getDeliveryRemarks() {
    return deliveryRemarks;
  }

  public void setDeliveryRemarks(@javax.annotation.Nullable String deliveryRemarks) {
    this.deliveryRemarks = deliveryRemarks;
  }


  public EDIWheelC11OrderCreationRequest blanketOrderReference(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestBlanketOrderReference blanketOrderReference) {
    this.blanketOrderReference = blanketOrderReference;
    return this;
  }

  /**
   * Get blanketOrderReference
   * @return blanketOrderReference
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestBlanketOrderReference getBlanketOrderReference() {
    return blanketOrderReference;
  }

  public void setBlanketOrderReference(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestBlanketOrderReference blanketOrderReference) {
    this.blanketOrderReference = blanketOrderReference;
  }


  public EDIWheelC11OrderCreationRequest customerReference(@javax.annotation.Nonnull EDIWheelC11OrderCreationRequestBlanketOrderReference customerReference) {
    this.customerReference = customerReference;
    return this;
  }

  /**
   * Get customerReference
   * @return customerReference
   */
  @javax.annotation.Nonnull
  public EDIWheelC11OrderCreationRequestBlanketOrderReference getCustomerReference() {
    return customerReference;
  }

  public void setCustomerReference(@javax.annotation.Nonnull EDIWheelC11OrderCreationRequestBlanketOrderReference customerReference) {
    this.customerReference = customerReference;
  }


  public EDIWheelC11OrderCreationRequest sellerParty(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestSellerParty sellerParty) {
    this.sellerParty = sellerParty;
    return this;
  }

  /**
   * Get sellerParty
   * @return sellerParty
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestSellerParty getSellerParty() {
    return sellerParty;
  }

  public void setSellerParty(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestSellerParty sellerParty) {
    this.sellerParty = sellerParty;
  }


  public EDIWheelC11OrderCreationRequest supplierParty(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestSellerParty supplierParty) {
    this.supplierParty = supplierParty;
    return this;
  }

  /**
   * Get supplierParty
   * @return supplierParty
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestSellerParty getSupplierParty() {
    return supplierParty;
  }

  public void setSupplierParty(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestSellerParty supplierParty) {
    this.supplierParty = supplierParty;
  }


  public EDIWheelC11OrderCreationRequest buyerParty(@javax.annotation.Nonnull EDIWheelC11OrderCreationRequestSellerParty buyerParty) {
    this.buyerParty = buyerParty;
    return this;
  }

  /**
   * Get buyerParty
   * @return buyerParty
   */
  @javax.annotation.Nonnull
  public EDIWheelC11OrderCreationRequestSellerParty getBuyerParty() {
    return buyerParty;
  }

  public void setBuyerParty(@javax.annotation.Nonnull EDIWheelC11OrderCreationRequestSellerParty buyerParty) {
    this.buyerParty = buyerParty;
  }


  public EDIWheelC11OrderCreationRequest orderingParty(@javax.annotation.Nullable EDIWheelC10DesadvRequestSellerParty orderingParty) {
    this.orderingParty = orderingParty;
    return this;
  }

  /**
   * Get orderingParty
   * @return orderingParty
   */
  @javax.annotation.Nullable
  public EDIWheelC10DesadvRequestSellerParty getOrderingParty() {
    return orderingParty;
  }

  public void setOrderingParty(@javax.annotation.Nullable EDIWheelC10DesadvRequestSellerParty orderingParty) {
    this.orderingParty = orderingParty;
  }


  public EDIWheelC11OrderCreationRequest consignee(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestConsignee consignee) {
    this.consignee = consignee;
    return this;
  }

  /**
   * Get consignee
   * @return consignee
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestConsignee getConsignee() {
    return consignee;
  }

  public void setConsignee(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestConsignee consignee) {
    this.consignee = consignee;
  }


  public EDIWheelC11OrderCreationRequest contract(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestBlanketOrderReference contract) {
    this.contract = contract;
    return this;
  }

  /**
   * Get contract
   * @return contract
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestBlanketOrderReference getContract() {
    return contract;
  }

  public void setContract(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestBlanketOrderReference contract) {
    this.contract = contract;
  }


  public EDIWheelC11OrderCreationRequest paymentTerms(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestPaymentTerms paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

  /**
   * Get paymentTerms
   * @return paymentTerms
   */
  @javax.annotation.Nullable
  public EDIWheelC11OrderCreationRequestPaymentTerms getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(@javax.annotation.Nullable EDIWheelC11OrderCreationRequestPaymentTerms paymentTerms) {
    this.paymentTerms = paymentTerms;
  }


  public EDIWheelC11OrderCreationRequest orderLine(@javax.annotation.Nullable List<EDIWheelC11OrderCreationRequestOrderLineInner> orderLine) {
    this.orderLine = orderLine;
    return this;
  }

  public EDIWheelC11OrderCreationRequest addOrderLineItem(EDIWheelC11OrderCreationRequestOrderLineInner orderLineItem) {
    if (this.orderLine == null) {
      this.orderLine = new ArrayList<>();
    }
    this.orderLine.add(orderLineItem);
    return this;
  }

  /**
   * Get orderLine
   * @return orderLine
   */
  @javax.annotation.Nullable
  public List<EDIWheelC11OrderCreationRequestOrderLineInner> getOrderLine() {
    return orderLine;
  }

  public void setOrderLine(@javax.annotation.Nullable List<EDIWheelC11OrderCreationRequestOrderLineInner> orderLine) {
    this.orderLine = orderLine;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EDIWheelC11OrderCreationRequest edIWheelC11OrderCreationRequest = (EDIWheelC11OrderCreationRequest) o;
    return Objects.equals(this.documentID, edIWheelC11OrderCreationRequest.documentID) &&
        Objects.equals(this.variant, edIWheelC11OrderCreationRequest.variant) &&
        Objects.equals(this.earliestDeliveryDate, edIWheelC11OrderCreationRequest.earliestDeliveryDate) &&
        Objects.equals(this.transportPriority, edIWheelC11OrderCreationRequest.transportPriority) &&
        Objects.equals(this.campaign, edIWheelC11OrderCreationRequest.campaign) &&
        Objects.equals(this.pickUp, edIWheelC11OrderCreationRequest.pickUp) &&
        Objects.equals(this.deliveryOption, edIWheelC11OrderCreationRequest.deliveryOption) &&
        Objects.equals(this.deliveryRemarks, edIWheelC11OrderCreationRequest.deliveryRemarks) &&
        Objects.equals(this.blanketOrderReference, edIWheelC11OrderCreationRequest.blanketOrderReference) &&
        Objects.equals(this.customerReference, edIWheelC11OrderCreationRequest.customerReference) &&
        Objects.equals(this.sellerParty, edIWheelC11OrderCreationRequest.sellerParty) &&
        Objects.equals(this.supplierParty, edIWheelC11OrderCreationRequest.supplierParty) &&
        Objects.equals(this.buyerParty, edIWheelC11OrderCreationRequest.buyerParty) &&
        Objects.equals(this.orderingParty, edIWheelC11OrderCreationRequest.orderingParty) &&
        Objects.equals(this.consignee, edIWheelC11OrderCreationRequest.consignee) &&
        Objects.equals(this.contract, edIWheelC11OrderCreationRequest.contract) &&
        Objects.equals(this.paymentTerms, edIWheelC11OrderCreationRequest.paymentTerms) &&
        Objects.equals(this.orderLine, edIWheelC11OrderCreationRequest.orderLine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentID, variant, earliestDeliveryDate, transportPriority, campaign, pickUp, deliveryOption, deliveryRemarks, blanketOrderReference, customerReference, sellerParty, supplierParty, buyerParty, orderingParty, consignee, contract, paymentTerms, orderLine);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EDIWheelC11OrderCreationRequest {\n");
    sb.append("    documentID: ").append(toIndentedString(documentID)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    earliestDeliveryDate: ").append(toIndentedString(earliestDeliveryDate)).append("\n");
    sb.append("    transportPriority: ").append(toIndentedString(transportPriority)).append("\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    pickUp: ").append(toIndentedString(pickUp)).append("\n");
    sb.append("    deliveryOption: ").append(toIndentedString(deliveryOption)).append("\n");
    sb.append("    deliveryRemarks: ").append(toIndentedString(deliveryRemarks)).append("\n");
    sb.append("    blanketOrderReference: ").append(toIndentedString(blanketOrderReference)).append("\n");
    sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
    sb.append("    sellerParty: ").append(toIndentedString(sellerParty)).append("\n");
    sb.append("    supplierParty: ").append(toIndentedString(supplierParty)).append("\n");
    sb.append("    buyerParty: ").append(toIndentedString(buyerParty)).append("\n");
    sb.append("    orderingParty: ").append(toIndentedString(orderingParty)).append("\n");
    sb.append("    consignee: ").append(toIndentedString(consignee)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    orderLine: ").append(toIndentedString(orderLine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DocumentID");
    openapiFields.add("Variant");
    openapiFields.add("EarliestDeliveryDate");
    openapiFields.add("TransportPriority");
    openapiFields.add("Campaign");
    openapiFields.add("PickUp");
    openapiFields.add("DeliveryOption");
    openapiFields.add("DeliveryRemarks");
    openapiFields.add("BlanketOrderReference");
    openapiFields.add("CustomerReference");
    openapiFields.add("SellerParty");
    openapiFields.add("SupplierParty");
    openapiFields.add("BuyerParty");
    openapiFields.add("OrderingParty");
    openapiFields.add("Consignee");
    openapiFields.add("Contract");
    openapiFields.add("PaymentTerms");
    openapiFields.add("OrderLine");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("DocumentID");
    openapiRequiredFields.add("CustomerReference");
    openapiRequiredFields.add("BuyerParty");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EDIWheelC11OrderCreationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EDIWheelC11OrderCreationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EDIWheelC11OrderCreationRequest is not found in the empty JSON string", EDIWheelC11OrderCreationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EDIWheelC11OrderCreationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EDIWheelC11OrderCreationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EDIWheelC11OrderCreationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("DocumentID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DocumentID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DocumentID").toString()));
      }
      if ((jsonObj.get("Variant") != null && !jsonObj.get("Variant").isJsonNull()) && !jsonObj.get("Variant").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Variant` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Variant").toString()));
      }
      if ((jsonObj.get("EarliestDeliveryDate") != null && !jsonObj.get("EarliestDeliveryDate").isJsonNull()) && !jsonObj.get("EarliestDeliveryDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EarliestDeliveryDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EarliestDeliveryDate").toString()));
      }
      if ((jsonObj.get("TransportPriority") != null && !jsonObj.get("TransportPriority").isJsonNull()) && !jsonObj.get("TransportPriority").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransportPriority` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransportPriority").toString()));
      }
      if ((jsonObj.get("Campaign") != null && !jsonObj.get("Campaign").isJsonNull()) && !jsonObj.get("Campaign").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Campaign` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Campaign").toString()));
      }
      if ((jsonObj.get("PickUp") != null && !jsonObj.get("PickUp").isJsonNull()) && !jsonObj.get("PickUp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PickUp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PickUp").toString()));
      }
      if ((jsonObj.get("DeliveryOption") != null && !jsonObj.get("DeliveryOption").isJsonNull()) && !jsonObj.get("DeliveryOption").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DeliveryOption` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DeliveryOption").toString()));
      }
      if ((jsonObj.get("DeliveryRemarks") != null && !jsonObj.get("DeliveryRemarks").isJsonNull()) && !jsonObj.get("DeliveryRemarks").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DeliveryRemarks` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DeliveryRemarks").toString()));
      }
      // validate the optional field `BlanketOrderReference`
      if (jsonObj.get("BlanketOrderReference") != null && !jsonObj.get("BlanketOrderReference").isJsonNull()) {
        EDIWheelC11OrderCreationRequestBlanketOrderReference.validateJsonElement(jsonObj.get("BlanketOrderReference"));
      }
      // validate the required field `CustomerReference`
      EDIWheelC11OrderCreationRequestBlanketOrderReference.validateJsonElement(jsonObj.get("CustomerReference"));
      // validate the optional field `SellerParty`
      if (jsonObj.get("SellerParty") != null && !jsonObj.get("SellerParty").isJsonNull()) {
        EDIWheelC11OrderCreationRequestSellerParty.validateJsonElement(jsonObj.get("SellerParty"));
      }
      // validate the optional field `SupplierParty`
      if (jsonObj.get("SupplierParty") != null && !jsonObj.get("SupplierParty").isJsonNull()) {
        EDIWheelC11OrderCreationRequestSellerParty.validateJsonElement(jsonObj.get("SupplierParty"));
      }
      // validate the required field `BuyerParty`
      EDIWheelC11OrderCreationRequestSellerParty.validateJsonElement(jsonObj.get("BuyerParty"));
      // validate the optional field `OrderingParty`
      if (jsonObj.get("OrderingParty") != null && !jsonObj.get("OrderingParty").isJsonNull()) {
        EDIWheelC10DesadvRequestSellerParty.validateJsonElement(jsonObj.get("OrderingParty"));
      }
      // validate the optional field `Consignee`
      if (jsonObj.get("Consignee") != null && !jsonObj.get("Consignee").isJsonNull()) {
        EDIWheelC11OrderCreationRequestConsignee.validateJsonElement(jsonObj.get("Consignee"));
      }
      // validate the optional field `Contract`
      if (jsonObj.get("Contract") != null && !jsonObj.get("Contract").isJsonNull()) {
        EDIWheelC11OrderCreationRequestBlanketOrderReference.validateJsonElement(jsonObj.get("Contract"));
      }
      // validate the optional field `PaymentTerms`
      if (jsonObj.get("PaymentTerms") != null && !jsonObj.get("PaymentTerms").isJsonNull()) {
        EDIWheelC11OrderCreationRequestPaymentTerms.validateJsonElement(jsonObj.get("PaymentTerms"));
      }
      if (jsonObj.get("OrderLine") != null && !jsonObj.get("OrderLine").isJsonNull()) {
        JsonArray jsonArrayorderLine = jsonObj.getAsJsonArray("OrderLine");
        if (jsonArrayorderLine != null) {
          // ensure the json data is an array
          if (!jsonObj.get("OrderLine").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `OrderLine` to be an array in the JSON string but got `%s`", jsonObj.get("OrderLine").toString()));
          }

          // validate the optional field `OrderLine` (array)
          for (int i = 0; i < jsonArrayorderLine.size(); i++) {
            EDIWheelC11OrderCreationRequestOrderLineInner.validateJsonElement(jsonArrayorderLine.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EDIWheelC11OrderCreationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EDIWheelC11OrderCreationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EDIWheelC11OrderCreationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EDIWheelC11OrderCreationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<EDIWheelC11OrderCreationRequest>() {
           @Override
           public void write(JsonWriter out, EDIWheelC11OrderCreationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EDIWheelC11OrderCreationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EDIWheelC11OrderCreationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EDIWheelC11OrderCreationRequest
   * @throws IOException if the JSON string is invalid with respect to EDIWheelC11OrderCreationRequest
   */
  public static EDIWheelC11OrderCreationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EDIWheelC11OrderCreationRequest.class);
  }

  /**
   * Convert an instance of EDIWheelC11OrderCreationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

