/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-17T19:36:32.994638751Z[GMT]", comments = "Generator version: 7.10.0")
public class EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner {
  public static final String SERIALIZED_NAME_DELIVERY_DATE = "deliveryDate";
  @SerializedName(SERIALIZED_NAME_DELIVERY_DATE)
  @javax.annotation.Nullable
  private String deliveryDate;

  public static final String SERIALIZED_NAME_DELIVERY_TIME = "deliveryTime";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TIME)
  @javax.annotation.Nullable
  private String deliveryTime;

  public static final String SERIALIZED_NAME_ORDER_BY_DATE = "orderByDate";
  @SerializedName(SERIALIZED_NAME_ORDER_BY_DATE)
  @javax.annotation.Nullable
  private String orderByDate;

  public static final String SERIALIZED_NAME_ORDER_BY_TIME = "orderByTime";
  @SerializedName(SERIALIZED_NAME_ORDER_BY_TIME)
  @javax.annotation.Nullable
  private String orderByTime;

  public static final String SERIALIZED_NAME_PICK_UP = "pickUp";
  @SerializedName(SERIALIZED_NAME_PICK_UP)
  @javax.annotation.Nullable
  private String pickUp;

  public static final String SERIALIZED_NAME_TRANSPORT_PRIORITY = "transportPriority";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_PRIORITY)
  @javax.annotation.Nullable
  private String transportPriority;

  public static final String SERIALIZED_NAME_AVAILABLE_QUANTITY = "availableQuantity";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_QUANTITY)
  @javax.annotation.Nullable
  private EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity availableQuantity;

  public static final String SERIALIZED_NAME_PRICE_DETAILS = "priceDetails";
  @SerializedName(SERIALIZED_NAME_PRICE_DETAILS)
  @javax.annotation.Nullable
  private EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails priceDetails;

  public static final String SERIALIZED_NAME_CHARGE = "charge";
  @SerializedName(SERIALIZED_NAME_CHARGE)
  @javax.annotation.Nullable
  private List<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner> charge = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUPPLIER_PARTY = "supplierParty";
  @SerializedName(SERIALIZED_NAME_SUPPLIER_PARTY)
  @javax.annotation.Nullable
  private EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty supplierParty;

  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner() {
  }

  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner deliveryDate(@javax.annotation.Nullable String deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

  /**
   * Get deliveryDate
   * @return deliveryDate
   */
  @javax.annotation.Nullable
  public String getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(@javax.annotation.Nullable String deliveryDate) {
    this.deliveryDate = deliveryDate;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner deliveryTime(@javax.annotation.Nullable String deliveryTime) {
    this.deliveryTime = deliveryTime;
    return this;
  }

  /**
   * Get deliveryTime
   * @return deliveryTime
   */
  @javax.annotation.Nullable
  public String getDeliveryTime() {
    return deliveryTime;
  }

  public void setDeliveryTime(@javax.annotation.Nullable String deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner orderByDate(@javax.annotation.Nullable String orderByDate) {
    this.orderByDate = orderByDate;
    return this;
  }

  /**
   * Get orderByDate
   * @return orderByDate
   */
  @javax.annotation.Nullable
  public String getOrderByDate() {
    return orderByDate;
  }

  public void setOrderByDate(@javax.annotation.Nullable String orderByDate) {
    this.orderByDate = orderByDate;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner orderByTime(@javax.annotation.Nullable String orderByTime) {
    this.orderByTime = orderByTime;
    return this;
  }

  /**
   * Get orderByTime
   * @return orderByTime
   */
  @javax.annotation.Nullable
  public String getOrderByTime() {
    return orderByTime;
  }

  public void setOrderByTime(@javax.annotation.Nullable String orderByTime) {
    this.orderByTime = orderByTime;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner pickUp(@javax.annotation.Nullable String pickUp) {
    this.pickUp = pickUp;
    return this;
  }

  /**
   * Get pickUp
   * @return pickUp
   */
  @javax.annotation.Nullable
  public String getPickUp() {
    return pickUp;
  }

  public void setPickUp(@javax.annotation.Nullable String pickUp) {
    this.pickUp = pickUp;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner transportPriority(@javax.annotation.Nullable String transportPriority) {
    this.transportPriority = transportPriority;
    return this;
  }

  /**
   * Get transportPriority
   * @return transportPriority
   */
  @javax.annotation.Nullable
  public String getTransportPriority() {
    return transportPriority;
  }

  public void setTransportPriority(@javax.annotation.Nullable String transportPriority) {
    this.transportPriority = transportPriority;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner availableQuantity(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity availableQuantity) {
    this.availableQuantity = availableQuantity;
    return this;
  }

  /**
   * Get availableQuantity
   * @return availableQuantity
   */
  @javax.annotation.Nullable
  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity getAvailableQuantity() {
    return availableQuantity;
  }

  public void setAvailableQuantity(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity availableQuantity) {
    this.availableQuantity = availableQuantity;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner priceDetails(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails priceDetails) {
    this.priceDetails = priceDetails;
    return this;
  }

  /**
   * Get priceDetails
   * @return priceDetails
   */
  @javax.annotation.Nullable
  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails getPriceDetails() {
    return priceDetails;
  }

  public void setPriceDetails(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails priceDetails) {
    this.priceDetails = priceDetails;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner charge(@javax.annotation.Nullable List<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner> charge) {
    this.charge = charge;
    return this;
  }

  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner addChargeItem(EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner chargeItem) {
    if (this.charge == null) {
      this.charge = new ArrayList<>();
    }
    this.charge.add(chargeItem);
    return this;
  }

  /**
   * Get charge
   * @return charge
   */
  @javax.annotation.Nullable
  public List<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner> getCharge() {
    return charge;
  }

  public void setCharge(@javax.annotation.Nullable List<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner> charge) {
    this.charge = charge;
  }


  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner supplierParty(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty supplierParty) {
    this.supplierParty = supplierParty;
    return this;
  }

  /**
   * Get supplierParty
   * @return supplierParty
   */
  @javax.annotation.Nullable
  public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty getSupplierParty() {
    return supplierParty;
  }

  public void setSupplierParty(@javax.annotation.Nullable EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty supplierParty) {
    this.supplierParty = supplierParty;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner = (EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner) o;
    return Objects.equals(this.deliveryDate, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.deliveryDate) &&
        Objects.equals(this.deliveryTime, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.deliveryTime) &&
        Objects.equals(this.orderByDate, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.orderByDate) &&
        Objects.equals(this.orderByTime, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.orderByTime) &&
        Objects.equals(this.pickUp, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.pickUp) &&
        Objects.equals(this.transportPriority, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.transportPriority) &&
        Objects.equals(this.availableQuantity, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.availableQuantity) &&
        Objects.equals(this.priceDetails, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.priceDetails) &&
        Objects.equals(this.charge, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.charge) &&
        Objects.equals(this.supplierParty, edIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.supplierParty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryDate, deliveryTime, orderByDate, orderByTime, pickUp, transportPriority, availableQuantity, priceDetails, charge, supplierParty);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner {\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    orderByDate: ").append(toIndentedString(orderByDate)).append("\n");
    sb.append("    orderByTime: ").append(toIndentedString(orderByTime)).append("\n");
    sb.append("    pickUp: ").append(toIndentedString(pickUp)).append("\n");
    sb.append("    transportPriority: ").append(toIndentedString(transportPriority)).append("\n");
    sb.append("    availableQuantity: ").append(toIndentedString(availableQuantity)).append("\n");
    sb.append("    priceDetails: ").append(toIndentedString(priceDetails)).append("\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("    supplierParty: ").append(toIndentedString(supplierParty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deliveryDate");
    openapiFields.add("deliveryTime");
    openapiFields.add("orderByDate");
    openapiFields.add("orderByTime");
    openapiFields.add("pickUp");
    openapiFields.add("transportPriority");
    openapiFields.add("availableQuantity");
    openapiFields.add("priceDetails");
    openapiFields.add("charge");
    openapiFields.add("supplierParty");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner is not found in the empty JSON string", EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deliveryDate") != null && !jsonObj.get("deliveryDate").isJsonNull()) && !jsonObj.get("deliveryDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryDate").toString()));
      }
      if ((jsonObj.get("deliveryTime") != null && !jsonObj.get("deliveryTime").isJsonNull()) && !jsonObj.get("deliveryTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryTime").toString()));
      }
      if ((jsonObj.get("orderByDate") != null && !jsonObj.get("orderByDate").isJsonNull()) && !jsonObj.get("orderByDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderByDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderByDate").toString()));
      }
      if ((jsonObj.get("orderByTime") != null && !jsonObj.get("orderByTime").isJsonNull()) && !jsonObj.get("orderByTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderByTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderByTime").toString()));
      }
      if ((jsonObj.get("pickUp") != null && !jsonObj.get("pickUp").isJsonNull()) && !jsonObj.get("pickUp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickUp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickUp").toString()));
      }
      if ((jsonObj.get("transportPriority") != null && !jsonObj.get("transportPriority").isJsonNull()) && !jsonObj.get("transportPriority").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transportPriority` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transportPriority").toString()));
      }
      // validate the optional field `availableQuantity`
      if (jsonObj.get("availableQuantity") != null && !jsonObj.get("availableQuantity").isJsonNull()) {
        EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerAvailableQuantity.validateJsonElement(jsonObj.get("availableQuantity"));
      }
      // validate the optional field `priceDetails`
      if (jsonObj.get("priceDetails") != null && !jsonObj.get("priceDetails").isJsonNull()) {
        EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerPriceDetails.validateJsonElement(jsonObj.get("priceDetails"));
      }
      if (jsonObj.get("charge") != null && !jsonObj.get("charge").isJsonNull()) {
        JsonArray jsonArraycharge = jsonObj.getAsJsonArray("charge");
        if (jsonArraycharge != null) {
          // ensure the json data is an array
          if (!jsonObj.get("charge").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `charge` to be an array in the JSON string but got `%s`", jsonObj.get("charge").toString()));
          }

          // validate the optional field `charge` (array)
          for (int i = 0; i < jsonArraycharge.size(); i++) {
            EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerChargeInner.validateJsonElement(jsonArraycharge.get(i));
          };
        }
      }
      // validate the optional field `supplierParty`
      if (jsonObj.get("supplierParty") != null && !jsonObj.get("supplierParty").isJsonNull()) {
        EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInnerSupplierParty.validateJsonElement(jsonObj.get("supplierParty"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner>() {
           @Override
           public void write(JsonWriter out, EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner
   * @throws IOException if the JSON string is invalid with respect to EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner
   */
  public static EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner.class);
  }

  /**
   * Convert an instance of EDIWheelC11StockInquiryResponseOrderLineInnerOrderedArticleScheduleDetailsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

