/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner {
  public static final String SERIALIZED_NAME_ALLOWANCE_OR_CHARGE_TYPE_CODE = "allowanceOrChargeTypeCode";
  @SerializedName(SERIALIZED_NAME_ALLOWANCE_OR_CHARGE_TYPE_CODE)
  @javax.annotation.Nullable
  private String allowanceOrChargeTypeCode;

  public static final String SERIALIZED_NAME_ALLOWANCE_OR_CHARGE_AMOUNT = "allowanceOrChargeAmount";
  @SerializedName(SERIALIZED_NAME_ALLOWANCE_OR_CHARGE_AMOUNT)
  @javax.annotation.Nullable
  private EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount allowanceOrChargeAmount;

  public EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner() {
  }

  public EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner allowanceOrChargeTypeCode(@javax.annotation.Nullable String allowanceOrChargeTypeCode) {
    this.allowanceOrChargeTypeCode = allowanceOrChargeTypeCode;
    return this;
  }

  /**
   * Allowance or charge type code. Example: Freight Charge (FC) &#x3D; total freight costs for shipments from Michelin DC.
   * @return allowanceOrChargeTypeCode
   */
  @javax.annotation.Nullable
  public String getAllowanceOrChargeTypeCode() {
    return allowanceOrChargeTypeCode;
  }

  public void setAllowanceOrChargeTypeCode(@javax.annotation.Nullable String allowanceOrChargeTypeCode) {
    this.allowanceOrChargeTypeCode = allowanceOrChargeTypeCode;
  }


  public EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner allowanceOrChargeAmount(@javax.annotation.Nullable EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount allowanceOrChargeAmount) {
    this.allowanceOrChargeAmount = allowanceOrChargeAmount;
    return this;
  }

  /**
   * Get allowanceOrChargeAmount
   * @return allowanceOrChargeAmount
   */
  @javax.annotation.Nullable
  public EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount getAllowanceOrChargeAmount() {
    return allowanceOrChargeAmount;
  }

  public void setAllowanceOrChargeAmount(@javax.annotation.Nullable EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount allowanceOrChargeAmount) {
    this.allowanceOrChargeAmount = allowanceOrChargeAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner edIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner = (EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner) o;
    return Objects.equals(this.allowanceOrChargeTypeCode, edIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.allowanceOrChargeTypeCode) &&
        Objects.equals(this.allowanceOrChargeAmount, edIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.allowanceOrChargeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowanceOrChargeTypeCode, allowanceOrChargeAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner {\n");
    sb.append("    allowanceOrChargeTypeCode: ").append(toIndentedString(allowanceOrChargeTypeCode)).append("\n");
    sb.append("    allowanceOrChargeAmount: ").append(toIndentedString(allowanceOrChargeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("allowanceOrChargeTypeCode");
    openapiFields.add("allowanceOrChargeAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner is not found in the empty JSON string", EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("allowanceOrChargeTypeCode") != null && !jsonObj.get("allowanceOrChargeTypeCode").isJsonNull()) && !jsonObj.get("allowanceOrChargeTypeCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `allowanceOrChargeTypeCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("allowanceOrChargeTypeCode").toString()));
      }
      // validate the optional field `allowanceOrChargeAmount`
      if (jsonObj.get("allowanceOrChargeAmount") != null && !jsonObj.get("allowanceOrChargeAmount").isJsonNull()) {
        EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInnerAllowanceOrChargeAmount.validateJsonElement(jsonObj.get("allowanceOrChargeAmount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.class));

       return (TypeAdapter<T>) new TypeAdapter<EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner>() {
           @Override
           public void write(JsonWriter out, EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner
   * @throws IOException if the JSON string is invalid with respect to EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner
   */
  public static EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner.class);
  }

  /**
   * Convert an instance of EDIWheelB34InvoiceListResponseInvoiceInnerAllowanceOrChargeInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

