/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner {
  public static final String SERIALIZED_NAME_PAYMENT_DUE_DATE = "paymentDueDate";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DUE_DATE)
  @javax.annotation.Nullable
  private String paymentDueDate;

  public static final String SERIALIZED_NAME_INSTALMENT_AMOUNT = "instalmentAmount";
  @SerializedName(SERIALIZED_NAME_INSTALMENT_AMOUNT)
  @javax.annotation.Nullable
  private EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount instalmentAmount;

  public EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner() {
  }

  public EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner paymentDueDate(@javax.annotation.Nullable String paymentDueDate) {
    this.paymentDueDate = paymentDueDate;
    return this;
  }

  /**
   * Invoice Payment Due Date. Payment due date could be one or multiple. Format YYYY-MM-DD.
   * @return paymentDueDate
   */
  @javax.annotation.Nullable
  public String getPaymentDueDate() {
    return paymentDueDate;
  }

  public void setPaymentDueDate(@javax.annotation.Nullable String paymentDueDate) {
    this.paymentDueDate = paymentDueDate;
  }


  public EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner instalmentAmount(@javax.annotation.Nullable EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount instalmentAmount) {
    this.instalmentAmount = instalmentAmount;
    return this;
  }

  /**
   * Get instalmentAmount
   * @return instalmentAmount
   */
  @javax.annotation.Nullable
  public EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount getInstalmentAmount() {
    return instalmentAmount;
  }

  public void setInstalmentAmount(@javax.annotation.Nullable EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount instalmentAmount) {
    this.instalmentAmount = instalmentAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner edIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner = (EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner) o;
    return Objects.equals(this.paymentDueDate, edIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.paymentDueDate) &&
        Objects.equals(this.instalmentAmount, edIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.instalmentAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentDueDate, instalmentAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner {\n");
    sb.append("    paymentDueDate: ").append(toIndentedString(paymentDueDate)).append("\n");
    sb.append("    instalmentAmount: ").append(toIndentedString(instalmentAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymentDueDate");
    openapiFields.add("instalmentAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner is not found in the empty JSON string", EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("paymentDueDate") != null && !jsonObj.get("paymentDueDate").isJsonNull()) && !jsonObj.get("paymentDueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentDueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentDueDate").toString()));
      }
      // validate the optional field `instalmentAmount`
      if (jsonObj.get("instalmentAmount") != null && !jsonObj.get("instalmentAmount").isJsonNull()) {
        EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInnerInstalmentAmount.validateJsonElement(jsonObj.get("instalmentAmount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.class));

       return (TypeAdapter<T>) new TypeAdapter<EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner>() {
           @Override
           public void write(JsonWriter out, EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner
   * @throws IOException if the JSON string is invalid with respect to EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner
   */
  public static EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner.class);
  }

  /**
   * Convert an instance of EDIWheelB34InvoiceListResponseInvoiceInnerPaymentTermsInnerPaymentNetInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

