/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact {
  public static final String SERIALIZED_NAME_CONTACT_ID = "contactId";
  @SerializedName(SERIALIZED_NAME_CONTACT_ID)
  @javax.annotation.Nullable
  private String contactId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private List<String> name = new ArrayList<>();

  public static final String SERIALIZED_NAME_TELEPHONE_NUMBER = "telephoneNumber";
  @SerializedName(SERIALIZED_NAME_TELEPHONE_NUMBER)
  @javax.annotation.Nullable
  private String telephoneNumber;

  public static final String SERIALIZED_NAME_TELEPHONE_EXTENSION = "telephoneExtension";
  @SerializedName(SERIALIZED_NAME_TELEPHONE_EXTENSION)
  @javax.annotation.Nullable
  private String telephoneExtension;

  public static final String SERIALIZED_NAME_FAX_NUMBER = "faxNumber";
  @SerializedName(SERIALIZED_NAME_FAX_NUMBER)
  @javax.annotation.Nullable
  private String faxNumber;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  @javax.annotation.Nullable
  private String emailAddress;

  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact() {
  }

  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact contactId(@javax.annotation.Nullable String contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * Get contactId
   * @return contactId
   */
  @javax.annotation.Nullable
  public String getContactId() {
    return contactId;
  }

  public void setContactId(@javax.annotation.Nullable String contactId) {
    this.contactId = contactId;
  }


  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact name(@javax.annotation.Nonnull List<String> name) {
    this.name = name;
    return this;
  }

  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact addNameItem(String nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<>();
    }
    this.name.add(nameItem);
    return this;
  }

  /**
   * This value would equal supplier party name returned in inventory inquiry response where order is to be sent. &lt;br&gt; In this example, request is to supplier &#x3D; Michelin (to ship from Michelin DC).
   * @return name
   */
  @javax.annotation.Nonnull
  public List<String> getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull List<String> name) {
    this.name = name;
  }


  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact telephoneNumber(@javax.annotation.Nullable String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
    return this;
  }

  /**
   * Get telephoneNumber
   * @return telephoneNumber
   */
  @javax.annotation.Nullable
  public String getTelephoneNumber() {
    return telephoneNumber;
  }

  public void setTelephoneNumber(@javax.annotation.Nullable String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }


  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact telephoneExtension(@javax.annotation.Nullable String telephoneExtension) {
    this.telephoneExtension = telephoneExtension;
    return this;
  }

  /**
   * Get telephoneExtension
   * @return telephoneExtension
   */
  @javax.annotation.Nullable
  public String getTelephoneExtension() {
    return telephoneExtension;
  }

  public void setTelephoneExtension(@javax.annotation.Nullable String telephoneExtension) {
    this.telephoneExtension = telephoneExtension;
  }


  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact faxNumber(@javax.annotation.Nullable String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

  /**
   * Get faxNumber
   * @return faxNumber
   */
  @javax.annotation.Nullable
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(@javax.annotation.Nullable String faxNumber) {
    this.faxNumber = faxNumber;
  }


  public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact emailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * Get emailAddress
   * @return emailAddress
   */
  @javax.annotation.Nullable
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact = (EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact) o;
    return Objects.equals(this.contactId, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.contactId) &&
        Objects.equals(this.name, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.name) &&
        Objects.equals(this.telephoneNumber, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.telephoneNumber) &&
        Objects.equals(this.telephoneExtension, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.telephoneExtension) &&
        Objects.equals(this.faxNumber, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.faxNumber) &&
        Objects.equals(this.emailAddress, edIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.emailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactId, name, telephoneNumber, telephoneExtension, faxNumber, emailAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact {\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    telephoneExtension: ").append(toIndentedString(telephoneExtension)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("contactId");
    openapiFields.add("name");
    openapiFields.add("telephoneNumber");
    openapiFields.add("telephoneExtension");
    openapiFields.add("faxNumber");
    openapiFields.add("emailAddress");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact is not found in the empty JSON string", EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("contactId") != null && !jsonObj.get("contactId").isJsonNull()) && !jsonObj.get("contactId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("name") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("name").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be an array in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("telephoneNumber") != null && !jsonObj.get("telephoneNumber").isJsonNull()) && !jsonObj.get("telephoneNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `telephoneNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("telephoneNumber").toString()));
      }
      if ((jsonObj.get("telephoneExtension") != null && !jsonObj.get("telephoneExtension").isJsonNull()) && !jsonObj.get("telephoneExtension").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `telephoneExtension` to be a primitive type in the JSON string but got `%s`", jsonObj.get("telephoneExtension").toString()));
      }
      if ((jsonObj.get("faxNumber") != null && !jsonObj.get("faxNumber").isJsonNull()) && !jsonObj.get("faxNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `faxNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("faxNumber").toString()));
      }
      if ((jsonObj.get("emailAddress") != null && !jsonObj.get("emailAddress").isJsonNull()) && !jsonObj.get("emailAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emailAddress").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.class));

       return (TypeAdapter<T>) new TypeAdapter<EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact>() {
           @Override
           public void write(JsonWriter out, EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact
   * @throws IOException if the JSON string is invalid with respect to EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact
   */
  public static EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact.class);
  }

  /**
   * Convert an instance of EDIWheelC11OrderCreationRequestAllOfSupplierPartyInformationContact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

