/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.michelin.adk.amn.JSON;

/**
 * Option 1: ManufacturersArticleID is used, and BuyersArticleID is not required
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ManufacturersArticleIDIsUsed {
  public static final String SERIALIZED_NAME_MANUFACTURERS_ARTICLE_I_D = "manufacturersArticleID";
  @SerializedName(SERIALIZED_NAME_MANUFACTURERS_ARTICLE_I_D)
  @javax.annotation.Nullable
  private Object manufacturersArticleID = null;

  public static final String SERIALIZED_NAME_BUYERS_ARTICLE_I_D = "buyersArticleID";
  @SerializedName(SERIALIZED_NAME_BUYERS_ARTICLE_I_D)
  @javax.annotation.Nullable
  private Object buyersArticleID = null;

  public ManufacturersArticleIDIsUsed() {
  }

  public ManufacturersArticleIDIsUsed manufacturersArticleID(@javax.annotation.Nullable Object manufacturersArticleID) {
    this.manufacturersArticleID = manufacturersArticleID;
    return this;
  }

  /**
   * Get manufacturersArticleID
   * @return manufacturersArticleID
   */
  @javax.annotation.Nullable
  public Object getManufacturersArticleID() {
    return manufacturersArticleID;
  }

  public void setManufacturersArticleID(@javax.annotation.Nullable Object manufacturersArticleID) {
    this.manufacturersArticleID = manufacturersArticleID;
  }


  public ManufacturersArticleIDIsUsed buyersArticleID(@javax.annotation.Nullable Object buyersArticleID) {
    this.buyersArticleID = buyersArticleID;
    return this;
  }

  /**
   * Get buyersArticleID
   * @return buyersArticleID
   */
  @javax.annotation.Nullable
  public Object getBuyersArticleID() {
    return buyersArticleID;
  }

  public void setBuyersArticleID(@javax.annotation.Nullable Object buyersArticleID) {
    this.buyersArticleID = buyersArticleID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManufacturersArticleIDIsUsed manufacturersArticleIDIsUsed = (ManufacturersArticleIDIsUsed) o;
    return Objects.equals(this.manufacturersArticleID, manufacturersArticleIDIsUsed.manufacturersArticleID) &&
        Objects.equals(this.buyersArticleID, manufacturersArticleIDIsUsed.buyersArticleID);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(manufacturersArticleID, buyersArticleID);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManufacturersArticleIDIsUsed {\n");
    sb.append("    manufacturersArticleID: ").append(toIndentedString(manufacturersArticleID)).append("\n");
    sb.append("    buyersArticleID: ").append(toIndentedString(buyersArticleID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("manufacturersArticleID");
    openapiFields.add("buyersArticleID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ManufacturersArticleIDIsUsed
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ManufacturersArticleIDIsUsed.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ManufacturersArticleIDIsUsed is not found in the empty JSON string", ManufacturersArticleIDIsUsed.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ManufacturersArticleIDIsUsed.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ManufacturersArticleIDIsUsed` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ManufacturersArticleIDIsUsed.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ManufacturersArticleIDIsUsed' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ManufacturersArticleIDIsUsed> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ManufacturersArticleIDIsUsed.class));

       return (TypeAdapter<T>) new TypeAdapter<ManufacturersArticleIDIsUsed>() {
           @Override
           public void write(JsonWriter out, ManufacturersArticleIDIsUsed value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ManufacturersArticleIDIsUsed read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ManufacturersArticleIDIsUsed given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ManufacturersArticleIDIsUsed
   * @throws IOException if the JSON string is invalid with respect to ManufacturersArticleIDIsUsed
   */
  public static ManufacturersArticleIDIsUsed fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ManufacturersArticleIDIsUsed.class);
  }

  /**
   * Convert an instance of ManufacturersArticleIDIsUsed to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

