/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryRequestBuyerParty;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryRequestConsignee;
import com.michelin.adk.amn.o2c.model.EDIWheelC11StockInquiryRequestOrderLineInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelC11StockInquiryRequest
 */
public class EDIWheelC11StockInquiryRequestTest {
    private final EDIWheelC11StockInquiryRequest model = new EDIWheelC11StockInquiryRequest();

    /**
     * Model tests for EDIWheelC11StockInquiryRequest
     */
    @Test
    public void testEDIWheelC11StockInquiryRequest() {
        // TODO: test EDIWheelC11StockInquiryRequest
    }

    /**
     * Test the property 'documentID'
     */
    @Test
    public void documentIDTest() {
        // TODO: test documentID
    }

    /**
     * Test the property 'variant'
     */
    @Test
    public void variantTest() {
        // TODO: test variant
    }

    /**
     * Test the property 'buyerParty'
     */
    @Test
    public void buyerPartyTest() {
        // TODO: test buyerParty
    }

    /**
     * Test the property 'consignee'
     */
    @Test
    public void consigneeTest() {
        // TODO: test consignee
    }

    /**
     * Test the property 'orderLine'
     */
    @Test
    public void orderLineTest() {
        // TODO: test orderLine
    }

}
