/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSummaryAllowanceOrChargeInner;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSummaryTaxDetailsInner;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationResponseChargeChargeAmount;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerSummary
 */
public class EDIWheelB44InvoiceListResponseInvoiceInnerSummaryTest {
    private final EDIWheelB44InvoiceListResponseInvoiceInnerSummary model = new EDIWheelB44InvoiceListResponseInvoiceInnerSummary();

    /**
     * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerSummary
     */
    @Test
    public void testEDIWheelB44InvoiceListResponseInvoiceInnerSummary() {
        // TODO: test EDIWheelB44InvoiceListResponseInvoiceInnerSummary
    }

    /**
     * Test the property 'allowanceOrCharge'
     */
    @Test
    public void allowanceOrChargeTest() {
        // TODO: test allowanceOrCharge
    }

    /**
     * Test the property 'totalAmount'
     */
    @Test
    public void totalAmountTest() {
        // TODO: test totalAmount
    }

    /**
     * Test the property 'taxableAmount'
     */
    @Test
    public void taxableAmountTest() {
        // TODO: test taxableAmount
    }

    /**
     * Test the property 'taxAmount'
     */
    @Test
    public void taxAmountTest() {
        // TODO: test taxAmount
    }

    /**
     * Test the property 'totalLineItemsAmount'
     */
    @Test
    public void totalLineItemsAmountTest() {
        // TODO: test totalLineItemsAmount
    }

    /**
     * Test the property 'totalChargeAmount'
     */
    @Test
    public void totalChargeAmountTest() {
        // TODO: test totalChargeAmount
    }

    /**
     * Test the property 'taxDetails'
     */
    @Test
    public void taxDetailsTest() {
        // TODO: test taxDetails
    }

}
