/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerAttachmentsInner;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerBuyerParty;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerConsignee;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerControls;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerEInvoicingIDInner;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerHeaderNote;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerInvoiceIssuerParty;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerInvoiceeParty;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInner;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerPaymentInstructions;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerPaymentTermsInner;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerReferences;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSummary;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelB44InvoiceListResponseInvoiceInner
 */
public class EDIWheelB44InvoiceListResponseInvoiceInnerTest {
    private final EDIWheelB44InvoiceListResponseInvoiceInner model = new EDIWheelB44InvoiceListResponseInvoiceInner();

    /**
     * Model tests for EDIWheelB44InvoiceListResponseInvoiceInner
     */
    @Test
    public void testEDIWheelB44InvoiceListResponseInvoiceInner() {
        // TODO: test EDIWheelB44InvoiceListResponseInvoiceInner
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'documentNumber'
     */
    @Test
    public void documentNumberTest() {
        // TODO: test documentNumber
    }

    /**
     * Test the property 'documentTypeCode'
     */
    @Test
    public void documentTypeCodeTest() {
        // TODO: test documentTypeCode
    }

    /**
     * Test the property 'documentFunctionCode'
     */
    @Test
    public void documentFunctionCodeTest() {
        // TODO: test documentFunctionCode
    }

    /**
     * Test the property 'documentFunctionText'
     */
    @Test
    public void documentFunctionTextTest() {
        // TODO: test documentFunctionText
    }

    /**
     * Test the property 'eInvoicingID'
     */
    @Test
    public void eInvoicingIDTest() {
        // TODO: test eInvoicingID
    }

    /**
     * Test the property 'environmentRegisterID'
     */
    @Test
    public void environmentRegisterIDTest() {
        // TODO: test environmentRegisterID
    }

    /**
     * Test the property 'goodsServiceIDCode'
     */
    @Test
    public void goodsServiceIDCodeTest() {
        // TODO: test goodsServiceIDCode
    }

    /**
     * Test the property 'goodsServiceIndication'
     */
    @Test
    public void goodsServiceIndicationTest() {
        // TODO: test goodsServiceIndication
    }

    /**
     * Test the property 'documentCurrency'
     */
    @Test
    public void documentCurrencyTest() {
        // TODO: test documentCurrency
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'buyerParty'
     */
    @Test
    public void buyerPartyTest() {
        // TODO: test buyerParty
    }

    /**
     * Test the property 'invoiceIssuerParty'
     */
    @Test
    public void invoiceIssuerPartyTest() {
        // TODO: test invoiceIssuerParty
    }

    /**
     * Test the property 'invoiceeParty'
     */
    @Test
    public void invoiceePartyTest() {
        // TODO: test invoiceeParty
    }

    /**
     * Test the property 'consignee'
     */
    @Test
    public void consigneeTest() {
        // TODO: test consignee
    }

    /**
     * Test the property 'sellerParty'
     */
    @Test
    public void sellerPartyTest() {
        // TODO: test sellerParty
    }

    /**
     * Test the property 'paymentTerms'
     */
    @Test
    public void paymentTermsTest() {
        // TODO: test paymentTerms
    }

    /**
     * Test the property 'paymentInstructions'
     */
    @Test
    public void paymentInstructionsTest() {
        // TODO: test paymentInstructions
    }

    /**
     * Test the property 'headerNote'
     */
    @Test
    public void headerNoteTest() {
        // TODO: test headerNote
    }

    /**
     * Test the property 'lineLevel'
     */
    @Test
    public void lineLevelTest() {
        // TODO: test lineLevel
    }

    /**
     * Test the property 'controls'
     */
    @Test
    public void controlsTest() {
        // TODO: test controls
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
