/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSellerPartyInformationContact;
import com.michelin.adk.amn.o2c.model.EDIWheelB44InvoiceListResponseInvoiceInnerSellerPartySupplierParty;
import com.michelin.adk.amn.o2c.model.EDIWheelC11OrderCreationRequestSellerPartyAddress;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty
 */
public class EDIWheelB44InvoiceListResponseInvoiceInnerSellerPartyTest {
    private final EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty model = new EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty();

    /**
     * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty
     */
    @Test
    public void testEDIWheelB44InvoiceListResponseInvoiceInnerSellerParty() {
        // TODO: test EDIWheelB44InvoiceListResponseInvoiceInnerSellerParty
    }

    /**
     * Test the property 'partyID'
     */
    @Test
    public void partyIDTest() {
        // TODO: test partyID
    }

    /**
     * Test the property 'agencyCode'
     */
    @Test
    public void agencyCodeTest() {
        // TODO: test agencyCode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'informationContact'
     */
    @Test
    public void informationContactTest() {
        // TODO: test informationContact
    }

    /**
     * Test the property 'supplierParty'
     */
    @Test
    public void supplierPartyTest() {
        // TODO: test supplierParty
    }

    /**
     * Test the property 'taxRegistrationID'
     */
    @Test
    public void taxRegistrationIDTest() {
        // TODO: test taxRegistrationID
    }

    /**
     * Test the property 'vaTRegistrationID'
     */
    @Test
    public void vaTRegistrationIDTest() {
        // TODO: test vaTRegistrationID
    }

    /**
     * Test the property 'siRENNumber'
     */
    @Test
    public void siRENNumberTest() {
        // TODO: test siRENNumber
    }

    /**
     * Test the property 'tribunalRegistrationNumber'
     */
    @Test
    public void tribunalRegistrationNumberTest() {
        // TODO: test tribunalRegistrationNumber
    }

    /**
     * Test the property 'companyLegalForm'
     */
    @Test
    public void companyLegalFormTest() {
        // TODO: test companyLegalForm
    }

    /**
     * Test the property 'companyRegisteredCapital'
     */
    @Test
    public void companyRegisteredCapitalTest() {
        // TODO: test companyRegisteredCapital
    }

}
