/*
 * Michelin North America Order-to-Cash APIs
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber
 */
public class EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumberTest {
    private final EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber model = new EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber();

    /**
     * Model tests for EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber
     */
    @Test
    public void testEDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber() {
        // TODO: test EDIWheelB34InvoiceListResponseInvoiceInnerReferencesSupplierClaimNumber
    }

    /**
     * Test the property 'documentID'
     */
    @Test
    public void documentIDTest() {
        // TODO: test documentID
    }

}
