/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics
 */
public class EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristicsTest {
    private final EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics model = new EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics();

    /**
     * Model tests for EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics
     */
    @Test
    public void testEDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics() {
        // TODO: test EDIWheelB44InvoiceListResponseInvoiceInnerLineLevelInnerArticleArticleCharacteristics
    }

    /**
     * Test the property 'noisePerformance'
     */
    @Test
    public void noisePerformanceTest() {
        // TODO: test noisePerformance
    }

    /**
     * Test the property 'noiseClassType'
     */
    @Test
    public void noiseClassTypeTest() {
        // TODO: test noiseClassType
    }

    /**
     * Test the property 'rollingResistance'
     */
    @Test
    public void rollingResistanceTest() {
        // TODO: test rollingResistance
    }

    /**
     * Test the property 'vehicleClass'
     */
    @Test
    public void vehicleClassTest() {
        // TODO: test vehicleClass
    }

    /**
     * Test the property 'wetGrip'
     */
    @Test
    public void wetGripTest() {
        // TODO: test wetGrip
    }

    /**
     * Test the property 'euDirectiveNumber'
     */
    @Test
    public void euDirectiveNumberTest() {
        // TODO: test euDirectiveNumber
    }

    /**
     * Test the property 'threePMSFMark'
     */
    @Test
    public void threePMSFMarkTest() {
        // TODO: test threePMSFMark
    }

    /**
     * Test the property 'iceGripPICT'
     */
    @Test
    public void iceGripPICTTest() {
        // TODO: test iceGripPICT
    }

    /**
     * Test the property 'URL5'
     */
    @Test
    public void URL5Test() {
        // TODO: test URL5
    }

}
