/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvRequestConsignee;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvRequestOrderedArticle;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvRequestReferences;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvRequestSellerParty;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelC10DesadvRequest
 */
public class EDIWheelC10DesadvRequestTest {
    private final EDIWheelC10DesadvRequest model = new EDIWheelC10DesadvRequest();

    /**
     * Model tests for EDIWheelC10DesadvRequest
     */
    @Test
    public void testEDIWheelC10DesadvRequest() {
        // TODO: test EDIWheelC10DesadvRequest
    }

    /**
     * Test the property 'documentID'
     */
    @Test
    public void documentIDTest() {
        // TODO: test documentID
    }

    /**
     * Test the property 'variant'
     */
    @Test
    public void variantTest() {
        // TODO: test variant
    }

    /**
     * Test the property 'despatchFromDate'
     */
    @Test
    public void despatchFromDateTest() {
        // TODO: test despatchFromDate
    }

    /**
     * Test the property 'despatchToDate'
     */
    @Test
    public void despatchToDateTest() {
        // TODO: test despatchToDate
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'sellerParty'
     */
    @Test
    public void sellerPartyTest() {
        // TODO: test sellerParty
    }

    /**
     * Test the property 'supplierParty'
     */
    @Test
    public void supplierPartyTest() {
        // TODO: test supplierParty
    }

    /**
     * Test the property 'buyerParty'
     */
    @Test
    public void buyerPartyTest() {
        // TODO: test buyerParty
    }

    /**
     * Test the property 'orderingParty'
     */
    @Test
    public void orderingPartyTest() {
        // TODO: test orderingParty
    }

    /**
     * Test the property 'consignee'
     */
    @Test
    public void consigneeTest() {
        // TODO: test consignee
    }

    /**
     * Test the property 'orderedArticle'
     */
    @Test
    public void orderedArticleTest() {
        // TODO: test orderedArticle
    }

}
