/*
 * Michelin North America Order-to-Cash APIs for dealers
 * These APIs will help you to do business transactions with Michelin.  <br><br><b>Authentication details:</b><br> <br><u>Option A:</u> OAuth2 Client Credentials (recommended) <br><u>Option B:</u> API Key + Basic Authentication (not recommended) <br><br>To request your access, please contact your representative. <br><br>Our services are based on the EDIWHEEL standards. <br>You can find more information on the <a href=\"https://www.ediwheel.com/\" target=\"_blank\">EDIWHEEL website</a>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcti-bs-ec-cit-support@michelin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.michelin.adk.amn.o2c.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.michelin.adk.amn.o2c.model.EDIWheelC10DesadvResponseDesadvInnerMeasuresGrossWeight;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EDIWheelC10DesadvResponseDesadvInnerMeasures
 */
public class EDIWheelC10DesadvResponseDesadvInnerMeasuresTest {
    private final EDIWheelC10DesadvResponseDesadvInnerMeasures model = new EDIWheelC10DesadvResponseDesadvInnerMeasures();

    /**
     * Model tests for EDIWheelC10DesadvResponseDesadvInnerMeasures
     */
    @Test
    public void testEDIWheelC10DesadvResponseDesadvInnerMeasures() {
        // TODO: test EDIWheelC10DesadvResponseDesadvInnerMeasures
    }

    /**
     * Test the property 'grossWeight'
     */
    @Test
    public void grossWeightTest() {
        // TODO: test grossWeight
    }

    /**
     * Test the property 'netWeight'
     */
    @Test
    public void netWeightTest() {
        // TODO: test netWeight
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

}
